### ISSUE TITLE
Clarification on the document field

### ISSUE THREAD

**Issue by pemontto** [ppi-ag/kibana-heatmap#1]
The requirements state heatmap expects a field in a specific format `[weekdayAsNumber]-[weekdayAsString]:[hourstart]-[hourend]` with the example  `1-Mo:23-24`.

Does heatmap accept ISO 8601 standards for week, weekday and hour?
E.g. Should the week number be zero padded, and is the range from 01-53 or 0-52
Most time libraries use 3 letter names for short week names, will they parse correctly?
Should the hourstart and hourend be zero spaced?

A quick look at the code says the zero spaced numbers should be fine as they're converted to ints.

Very excited to get this going, but it's not working for me at the moment

**Comment by pkanthi** [comment]
I am trying to make this work with no luck. I see that the widget is trying to interpret the 'time-slot' value as data. I have set the 'Field' to my 'heatmap' variable that has format of '5-Fri:04-05'.

So i see values like '5-Fri:04-05', '5-Fri:03-04', etc.... on the records. But when i just can't load the data. Printing 'label' value from ' parseTimeSlotLabel' function gives following output in console.

![image](https://cloud.githubusercontent.com/assets/9375834/6407382/fe0071d2-be04-11e4-97b2-a5c27e38cec9.png)

Under Queries, i selected 'All Events' (Is this correct?)

![image](https://cloud.githubusercontent.com/assets/9375834/6407397/215d1ea0-be05-11e4-8a7d-91bc97e7f344.png)

![image](https://cloud.githubusercontent.com/assets/9375834/6407409/405af5b6-be05-11e4-861a-780ec814e5cd.png)

Appreciate the help.

**Comment by LukasHavemann** [comment]
I think the problem is that you have the wrong mapping for your field. For a detailed explanation look at issue #3
