### ISSUE TITLE
Heatmap - wrong placement / incorrect labeleling

### ISSUE THREAD

**Issue by Chadwiki** [ppi-ag/kibana-heatmap#5]
I have noticed that all heatmap cell data is either off or mislabeled. 
While the label is shown for a cell on mouse over, the label does not correspond correctly to cell location. 
ie. cell in Mon 2h shows Sat:01-02, sat 16h slot shows fr:15-17
I'm not sure if everything is offset by one day or the issue is with the time-slot data. 

Attached example: Fri:23h slot cell label is Thu:22-23, Su:24h slot cell label 7-Sat:23-01
![heat](https://cloud.githubusercontent.com/assets/6718884/4389867/bb42a882-43f8-11e4-9d5d-806d58f27716.JPG)

**Comment by LukasHavemann** [comment]
This project is not actively maintained. Closed issue due to archiving of the project.
